
{@@topic_welcome
<title Welcome to Bare Game>
<include topic_welcome.txt>}

	{@@topic_introduction 
	<title Introducing Bare Game>
	<group topic_welcome>
	<include topic_introduction.txt>}

	{@@topic_whats_new 
	<title What&apos;s New>
	<group topic_welcome>
	<include topic_whats_new.txt>}

	{@@topic_getting_started
	<title Getting Started>
	<group topic_welcome>
	<include topic_getting_started.txt>}

	  {@@topic_installation
	  <title Installation>
	  <group topic_getting_started>
	  <include topic_installation.txt>}

  	  {@@topic_hello_game_world
  	  <title Hello World>
  	  <group topic_getting_started>
  	  <include topic_hello_world.txt>}
  	  
	{@@topic_organised
	<title How Everything is Organised>
	<group topic_welcome>
	<include topic_organised.txt>}

{@@topic_core_concepts
<title Core Concepts>
<include topic_core_concepts.txt>}

  {@@topic_using_lazarus
  <title Using the Lazarus IDE>
  <group topic_core_concepts>
  <include topic_using_lazarus.txt>}
  
  {@@topic_application 
  <title Using the Application object>
  <group topic_core_concepts>
  <include topic_application.txt>}
  
  {@@topic_window 
  <title Creating a game window>
  <group topic_core_concepts>
  <include topic_window.txt>}
  
{@@topic_important_information
<title Important Information>
<include topic_important_information.txt>}
  
	{@@topic_acknowledgements 
	<title Acknowledgements>
	<group topic_important_information>
	<include topic_acknowledgements.txt>}

	{@@topic_resources 
	<title Resources>
	<group topic_important_information>
	<include topic_resources.txt>}
	
	{@@topic_known_issues 
	<title Known issues>
	<group topic_important_information>
	<include topic_known_issues.txt>}

{@@topic_category
<title Functionality>
<group Bare>
<include topic_category.txt>}

{@@topic_string
<title String Handling>
<group topic_category>
<include topic_string.txt>}
